/**
 * Do not edit directly
 * Generated on Tue, 15 Feb 2022 19:15:12 GMT
 */

export const ColorCoreNeutral0 : string;
export const ColorCoreNeutral100 : string;
export const ColorCoreNeutral200 : string;
export const ColorCoreNeutral400 : string;
export const ColorCoreNeutral700 : string;
export const ColorCorePrimary100 : string;
export const ColorCorePrimary200 : string;
export const ColorCorePrimary300 : string;
export const ColorCorePrimary400 : string;
export const ColorCorePrimary500 : string;
export const ColorCorePrimary600 : string;
export const ColorCorePrimary700 : string;
export const ColorCoreDanger100 : string;
export const ColorCoreDanger200 : string;
export const ColorCoreDanger300 : string;
export const ColorCoreDanger400 : string;
export const ColorCoreDanger500 : string;
export const ColorCoreDanger600 : string;
export const ColorCoreDanger700 : string;
export const ColorCoreSuccess100 : string;
export const ColorCoreSuccess200 : string;
export const ColorCoreSuccess300 : string;
export const ColorCoreSuccess400 : string;
export const ColorCoreSuccess500 : string;
export const ColorCoreSuccess600 : string;
export const ColorCoreSuccess700 : string;
export const ColorCoreWarning100 : string;
export const ColorCoreWarning200 : string;
export const ColorCoreWarning300 : string;
export const ColorCoreWarning400 : string;
export const ColorCoreWarning500 : string;
export const ColorCoreWarning600 : string;
export const ColorCoreWarning700 : string;
export const ColorTextPrimary : string;
export const ColorTextSecondary : string;
export const ColorTextSuccess : string;
export const ColorTextWarning : string;
export const ColorTextDanger : string;
export const ColorBackgroundBody : string;
export const ColorBackgroundUi : string;
export const ColorBackgroundInteraction : string;
export const ColorBackgroundNotification : string;
export const ColorBorderFocus : string;
export const ColorBorderLight : string;
export const ColorBorderDark : string;
export const FontFamiliesLato : string;
export const FontFamiliesDmSans : string;
export const LineHeights0 : number;
export const LineHeights1 : number;
export const LineHeights2 : number;
export const LineHeights3 : number;
export const LineHeights4 : number;
export const LineHeights5 : number;
export const LineHeights6 : number;
export const LineHeights7 : number;
export const FontWeightsLato0 : string;
export const FontWeightsDmSans1 : string;
export const FontSize0 : number;
export const FontSize1 : number;
export const FontSize2 : number;
export const FontSize3 : number;
export const FontSize4 : number;
export const FontSize5 : number;
export const FontSize6 : number;
export const FontSize7 : number;
export const LetterSpacing0 : string;
export const ParagraphSpacing0 : number;
export const BodyXl : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodyLg : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodyMd : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodySm : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodyXs : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head1 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head2 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head3 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head4 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head5 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head6 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const TextCaseNone : string;
export const TextDecorationNone : string;