/**
 * Do not edit directly
 * Generated on Tue, 15 Feb 2022 16:07:51 GMT
 */

export const CoreNeutral0 : string;
export const CoreNeutral100 : string;
export const CoreNeutral200 : string;
export const CoreNeutral400 : string;
export const CoreNeutral700 : string;
export const CorePrimary100 : string;
export const CorePrimary200 : string;
export const CorePrimary300 : string;
export const CorePrimary400 : string;
export const CorePrimary500 : string;
export const CorePrimary600 : string;
export const CorePrimary700 : string;
export const CoreDanger100 : string;
export const CoreDanger200 : string;
export const CoreDanger300 : string;
export const CoreDanger400 : string;
export const CoreDanger500 : string;
export const CoreDanger600 : string;
export const CoreDanger700 : string;
export const CoreSuccess100 : string;
export const CoreSuccess200 : string;
export const CoreSuccess300 : string;
export const CoreSuccess400 : string;
export const CoreSuccess500 : string;
export const CoreSuccess600 : string;
export const CoreSuccess700 : string;
export const CoreWarning100 : string;
export const CoreWarning200 : string;
export const CoreWarning300 : string;
export const CoreWarning400 : string;
export const CoreWarning500 : string;
export const CoreWarning600 : string;
export const CoreWarning700 : string;
export const InterfaceBackgroundColor : string;
export const InterfaceForegroundColor : string;
export const InterfaceColorFocus : string;
export const InterfaceBorderColorLight : string;
export const InterfaceBorderColorDark : string;
export const InterfaceColorInteraction : string;
export const InterfaceColorNotification : string;
export const InterfaceTextColorPrimary : string;
export const InterfaceTextColorSecondary : string;
export const InterfaceTextColorSuccess : string;
export const InterfaceTextColorWarning : string;
export const InterfaceTextColorDanger : string;