/**
 * Do not edit directly
 * Generated on Tue, 15 Feb 2022 16:10:05 GMT
 */

export const CoreNeutral0 : string;
export const CoreNeutral100 : string;
export const CoreNeutral200 : string;
export const CoreNeutral400 : string;
export const CoreNeutral700 : string;
export const CorePrimary100 : string;
export const CorePrimary200 : string;
export const CorePrimary300 : string;
export const CorePrimary400 : string;
export const CorePrimary500 : string;
export const CorePrimary600 : string;
export const CorePrimary700 : string;
export const CoreDanger100 : string;
export const CoreDanger200 : string;
export const CoreDanger300 : string;
export const CoreDanger400 : string;
export const CoreDanger500 : string;
export const CoreDanger600 : string;
export const CoreDanger700 : string;
export const CoreSuccess100 : string;
export const CoreSuccess200 : string;
export const CoreSuccess300 : string;
export const CoreSuccess400 : string;
export const CoreSuccess500 : string;
export const CoreSuccess600 : string;
export const CoreSuccess700 : string;
export const CoreWarning100 : string;
export const CoreWarning200 : string;
export const CoreWarning300 : string;
export const CoreWarning400 : string;
export const CoreWarning500 : string;
export const CoreWarning600 : string;
export const CoreWarning700 : string;
export const InterfaceBackgroundColor : string;
export const InterfaceForegroundColor : string;
export const InterfaceColorFocus : string;
export const InterfaceBorderColorLight : string;
export const InterfaceBorderColorDark : string;
export const InterfaceColorInteraction : string;
export const InterfaceColorNotification : string;
export const InterfaceTextColorPrimary : string;
export const InterfaceTextColorSecondary : string;
export const InterfaceTextColorSuccess : string;
export const InterfaceTextColorWarning : string;
export const InterfaceTextColorDanger : string;
export const FontFamiliesLato : string;
export const FontFamiliesDmSans : string;
export const LineHeights0 : number;
export const LineHeights1 : number;
export const LineHeights2 : number;
export const LineHeights3 : number;
export const LineHeights4 : number;
export const LineHeights5 : number;
export const LineHeights6 : number;
export const LineHeights7 : number;
export const FontWeightsLato0 : string;
export const FontWeightsDmSans1 : string;
export const FontSize0 : number;
export const FontSize1 : number;
export const FontSize2 : number;
export const FontSize3 : number;
export const FontSize4 : number;
export const FontSize5 : number;
export const FontSize6 : number;
export const FontSize7 : number;
export const LetterSpacing0 : string;
export const ParagraphSpacing0 : number;
export const BodyXl : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodyLg : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodyMd : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodySm : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const BodyXs : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head1 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head2 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head3 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head4 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head5 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const Head6 : { fontFamily: string, fontWeight: string, lineHeight: number, fontSize: number, letterSpacing: string, paragraphSpacing: number, textCase: string, textDecoration: string };
export const TextCaseNone : string;
export const TextDecorationNone : string;