name: Beta Pre-release

on:
  push:
    branches:
      - beta

permissions:
  contents: write
  pull-requests: write

jobs:
  release-beta:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.beta.json

  publish:
    needs: release-beta
    if: ${{ fromJSON(needs.release-beta.outputs.releases_created) }}
    uses: ./.github/workflows/build-and-publish.yml
    with:
      publish-script: "publish:beta"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
