name: Release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-stable.outputs.releases_created || steps.release-beta.outputs.releases_created || false }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release (stable)
        if: github.ref == 'refs/heads/main'
        uses: googleapis/release-please-action@v4
        id: release-stable
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Release (beta)
        if: github.ref == 'refs/heads/beta'
        uses: googleapis/release-please-action@v4
        id: release-beta
        with:
          target-branch: beta
          config-file: release-please-config.beta.json
          manifest-file: .release-please-manifest.beta.json
          versioning-strategy: prerelease

  publish:
    needs: release
    if: ${{ fromJSON(needs.release.outputs.releases_created) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Install (again - testing...)
        run: pnpm install

      - name: Publish to npm
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            pnpm run publish
          else
            pnpm run publish:beta
          fi
