name: 'Tokens: publish release'
on:
  create:
    tags:
      - '@haiilo/catalyst-tokens/v*'
  workflow_run:
    workflows:
      - 'Tokens: create release'
    types:
      - completed
defaults:
  run:
    working-directory: tokens
jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: tokens/package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: tokens/package.json
