name: 'Tokens: create release'
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release level'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch
defaults:
  run:
    working-directory: tokens
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: tokens/package-lock.json
      - name: Install and Build
        run: |
          npm ci
          npm run build
      - name: Create Release
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          npm run release:${{ github.event.inputs.release }}
      - name: Commit files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push --follow-tags
